Change api url
praveen-garg/FogLAMP pull request #27
Opened 2017-10-09 11:37 UTC by mshariq-nerd

Configure api end points using settings.

2017-10-09 13:54 UTC, praveen-garg requested changes
LGTM from dry run review; need minor chnages and testing as fresh and rerun with manual deletion of localStorage on ff, safari and chrome

2017-10-09 13:54 UTC, praveen-garg commented on src/frontend/src/app/settings/settings.component.html
> +      <label class='label'>IP Address</label>
Host IP or Address

2017-10-09 13:54 UTC, praveen-garg commented on src/frontend/src/app/settings/settings.component.html
> +        <button class='button is-primary is-pulled-right' (click)='resetEndPoint()'>Reset URL</button>
Set the URL and Restart

2017-10-09 13:54 UTC, praveen-garg commented on src/frontend/src/app/settings/settings.component.ts
> +    const ipField = <HTMLInputElement>document.getElementById('ip');
hostField host can have IP or other valid address

2017-10-09 13:54 UTC, praveen-garg commented on src/frontend/src/app/settings/settings.component.ts
> +    const ip_address = protocolField.value + '://' + ipField.value + ':' + portField.value + '/foglamp/';
endpoint =

2017-10-09 13:54 UTC, praveen-garg commented on src/frontend/src/app/settings/settings.component.ts
> +    window.location.reload();
is this angular way?

2017-10-10 09:22 UTC, monika-Dianomic commented
Tested on Safari, Chrome and Firefox. All things are working fine except one thing, in Safari and Firefox, after clicking the button `Set the URL & Restart` it is not redirecting to Home Page (Dashboard). It remains on Setting Tab.

2017-10-11 09:37 UTC, mshariq-nerd commented
Route redirection issue fixed on Firefox and Safari browser.

2017-10-11 09:45 UTC, mshariq-nerd commented
@praveen-garg You can merge this PR now.

2017-10-11 09:59 UTC, praveen-garg approved these changes

2017-10-11 10:00 UTC, merged