Added css file locally, removed fontawesome library
praveen-garg/FogLAMP pull request #3
Opened 2017-07-04 13:15 UTC by mshariq-nerd

2017-07-04 17:37 UTC, praveen-garg requested changes
minor fix needed

2017-07-04 17:37 UTC, praveen-garg commented on src/frontend/src/app/footer/footer.component.html
> -          <i class="fa fa-github"></i>
<a target="_blank" href="https://github.com/foglamp/FogLAMP"> source code on Github </a>

2017-07-04 17:39 UTC, praveen-garg requested changes

2017-07-04 17:39 UTC, praveen-garg commented on src/frontend/src/app/app.component.ts
> +import '../assets/css/bulma.min.css';
delete styles.css as well from assets

2017-07-05 06:26 UTC, mshariq-nerd commented
@praveen-garg  changes done. Please review and merge

2017-07-05 07:18 UTC, praveen-garg approved these changes

2017-07-05 07:18 UTC, merged