Fixed service management port issue
praveen-garg/FogLAMP pull request #37
Opened 2017-11-09 17:06 UTC by mshariq-nerd

2017-11-09 17:44 UTC, praveen-garg requested changes
minor changes! only log the stuff which matters

2017-11-09 17:44 UTC, praveen-garg commented on src/frontend/src/app/settings/settings.component.ts
> +      console.log(url_items);
remove this

2017-11-09 17:44 UTC, praveen-garg commented on src/frontend/src/environments/environment.prod.ts
> +  BASE_URL: localStorage.getItem('SERVICE_URL') == null ? 'http://0.0.0.0:8082/foglamp/' : localStorage.getItem('SERVICE_URL'),
'http://0.0.0.0:8082/foglamp/ make 8082 to 8081 rest is valid for prod

2017-11-09 17:44 UTC, praveen-garg commented on src/frontend/src/app/services-health/services-health.component.ts
>          console.log('error: ', error);
if error then  (if could not connect; show warning message "Could not connect to Core Managment API, Make sure to set correct [core management port](/settings)" with link to navigate to settings page to fill up core port)

2017-11-09 17:44 UTC, praveen-garg commented on src/frontend/src/app/settings/settings.component.html
> +      <input id='port' class='input' type='number' maxlength="4" placeholder='8081' [ngModel]='port'>
if possible call it id='service_port'

2017-11-09 17:47 UTC, praveen-garg commented
just below or next to "Services Status" add a light color tag with `Last updated at: Jan 26, 2017 15:23:12`

2017-11-10 09:44 UTC, mshariq-nerd commented
@praveen-garg Fixed per feedback. Please review now.

2017-11-10 09:49 UTC, praveen-garg reviewed
1 question; 1 minor change and we are good to go

2017-11-10 09:49 UTC, praveen-garg commented on src/frontend/src/app/directives/alert.component.html
> +<div [innerHTML]="message.text" id = "alert" *ngIf="message" [ngClass]="{ 'notification': message, 'is-success': message.type === 'success', 'is-danger': message.type === 'error','is-warning': messag
do we need {{message.text}} as innerText now? as we have innerHTML

2017-11-10 09:49 UTC, praveen-garg commented on src/frontend/src/app/utils.ts
> +  public static getCureentDate() {
getCurrentDate

2017-11-10 10:01 UTC, praveen-garg commented
clear the local storage and start new; I don't see any warning on services-health page

2017-11-10 10:20 UTC, praveen-garg approved these changes

2017-11-10 10:20 UTC, merged