Added graph and trends of asset
praveen-garg/FogLAMP pull request #42
Opened 2017-11-14 15:02 UTC by mshariq-nerd

1)  Added asset summary, trends

TODO:
1) Readings Summary on graph
2) Time base graph trends

2017-11-15 08:08 UTC, MonikaSharma06 requested changes

2017-11-15 08:08 UTC, MonikaSharma06 commented on src/frontend/src/app/foglamp-asset/assets/assets.component.html
> +          <my-pagination [count]=t his.recordCount [page]="page" [perPage]=t his.limit [pagesToShow]="3" (goPrev)="onPrev()" (goNext)="onNext()"
Space between `t` and `h`. (Pagination is not working because of this)

2017-11-15 08:08 UTC, monika-Dianomic commented on src/frontend/src/app/foglamp-asset/asset-summary/asset-summary.component.ts
> +        // get kyes of the readings
misspelled `keys`

2017-11-15 09:17 UTC, MonikaSharma06 requested changes

2017-11-15 09:17 UTC, monika-Dianomic commented on src/frontend/src/app/foglamp-asset/assets/assets.component.html
> +          <my-pagination [count]=this.recordCount [page]="page" [perPage]=t his.limit [pagesToShow]="3" (goPrev)="onPrev()" (goNext)="onNext()"
There is also space between `t` and `h` in `[perPage]=t his.limit`

2017-11-15 09:24 UTC, MonikaSharma06 approved these changes

2017-11-17 13:23 UTC, mshariq-nerd commented
Closing this PR in favour of [PR#45](https://github.com/praveen-garg/FogLAMP/pull/45)

2017-11-17 13:23 UTC, closed without merging