Fixed pagination component issue
praveen-garg/FogLAMP pull request #48
Opened 2017-11-20 13:37 UTC by mshariq-nerd

2017-11-20 13:45 UTC, praveen-garg requested changes

2017-11-20 13:45 UTC, praveen-garg commented on src/frontend/src/app/asset-readings/assets/assets.component.ts
> +      offset = 1;
this.offset?

2017-11-20 13:45 UTC, praveen-garg commented on src/frontend/src/app/audit-log/audit-log.component.ts
> +        this.filterdData = [{
make it object instead of array

2017-11-20 13:45 UTC, praveen-garg commented on src/frontend/src/app/audit-log/audit-log.component.ts
> +          count: 100                // TODO: FOGL-714. For now it is hard coded.
totalCount

2017-11-20 13:58 UTC, praveen-garg requested changes

2017-11-20 13:58 UTC, praveen-garg commented on src/frontend/src/app/pagination/pagination.component.html
> +  <button class="button pagination-previous" (click)="onPrev()" [disabled]="page === 1">{{ page-1 }}&nbsp;<i class="fa fa-caret-left" aria-hidden="true"></i></button>
page ==1 ? '': page-1

2017-11-20 13:58 UTC, praveen-garg commented on src/frontend/src/app/pagination/pagination.component.html
> +  <button class="button pagination-next" (click)="onNext()" [disabled]="lastPage()"><i class="fa fa-caret-right" aria-hidden="true">&nbsp; {{ page !== totalPage ? page + 1 : totalPage }}</i></button>
page == totalPage ? '' : page + 1

2017-11-20 14:36 UTC, praveen-garg approved these changes

2017-11-20 14:40 UTC, praveen-garg commented
LGTM! with 2 known issues:

1) filteredData should be local scope var and let's have binding for `logs` and `totalCount` variables. Or  just have a single object `audit` with 2 keys `logs` and `totalCount`; 

2) remove hardcoded 100

2017-11-20 19:07 UTC, praveen-garg commented on src/frontend/src/app/pagination/pagination.component.ts
> +import { Component, EventEmitter, Input, Output, OnInit, SimpleChanges, OnChanges } from '@angular/core';
@mshariq-nerd  review these import

2017-11-21 08:54 UTC, mshariq-nerd commented on src/frontend/src/app/pagination/pagination.component.ts
> +import { Component, EventEmitter, Input, Output, OnInit, SimpleChanges, OnChanges } from '@angular/core';
@praveen-garg All are required import.

2017-11-21 09:01 UTC, merged