Fixed configuration indexing issue
praveen-garg/FogLAMP pull request #8
Opened 2017-08-17 20:22 UTC by mshariq-nerd

2017-08-17 20:28 UTC, praveen-garg requested changes
save button color should be "primary"

2017-08-17 20:28 UTC, praveen-garg commented on src/frontend/src/app/configuration-manager/configuration-manager.component.ts
> +  private getCategory(category_name: string, description:string): void {
category_description as first arg

2017-08-17 20:28 UTC, praveen-garg commented on src/frontend/src/app/configuration-manager/configuration-manager.component.ts
> +        this.categoryData.push({description: description,key: category_name, value: categoryValues})
key, description, value or key, value, description

and space after comma

2017-08-17 20:28 UTC, praveen-garg commented on src/frontend/src/app/configuration-manager/configuration-manager.component.ts
> -
thanks for removing this

2017-08-17 20:33 UTC, mshariq-nerd commented
@praveen-garg Please review now.

2017-08-17 21:17 UTC, praveen-garg requested changes

2017-08-17 21:17 UTC, praveen-garg commented on src/frontend/src/app/configuration-manager/configuration-manager.component.ts
> +          this.getCategory(element.key, element.description);
order x, y and accepted as y, x?

2017-08-24 12:51 UTC, praveen-garg commented
@mshariq-nerd  please rebase with frontend

2017-08-24 12:52 UTC, praveen-garg commented on src/frontend/src/app/configuration-manager/configuration-manager.component.html
> -                    <p class="title is-5">{{v?.key}}</p>
don't delete; just comment it

2017-08-26 17:37 UTC, praveen-garg approved these changes

2017-08-26 17:37 UTC, merged